version: "2"

run:
  go: "1.22"
  timeout: 3m

linters:
  default: none
  enable:
    - govet
    - staticcheck

formatters:
  enable:
    - gofumpt
    - gci
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - prefix(github.com/sagernet/)
        - default
